name: Print Summary
on: [push, pull_request]

jobs:
  Print-Summary:
    runs-on: ubuntu-latest
    steps:
      - run: echo "======= EVERY PUSH ========"
      - run: echo "OS ${{ runner.os }}"
      - run: echo "Repository ${{ github.repository }}"
      - run: echo "Event ${{ github.event_name }}"
      - run: echo "Branch ${{ github.ref }}"

# merge_job:
#   if: github.event.pull_request.merged == true
#   runs-on: ubuntu-latest
#   steps:
#   - run: |
#       echo PR #${{ github.event.number }} has been merged